Repository B0XERCAT/fool-proof, pull requests merged in 2024-08, with the labels that each got.

#2 chore: refactor dockerfile
  .dockerignore
  Dockerfile
  docker-compose.yaml
Labels: enhancement

#4 refactor: reorganize project folder structure
  README.md
  client/.eslintrc.json
  client/.gitignore
  client/.prettierrc
  client/README.md
  client/app/globals.css
  client/app/layout.tsx
  client/app/page.tsx
  client/components.json
  client/components/ui/button.tsx
  client/lib/utils.ts
  client/next.config.mjs
  client/package.json
  client/pnpm-lock.yaml
  client/postcss.config.mjs
  client/tailwind.config.ts
  client/tsconfig.json
  server/README.md
Labels: enhancement

#6 refactor: edit docker related files and directories
  client/.dockerignore
  client/Dockerfile
  docker-compose.yaml
  server/.dockerignore
  server/Dockerfile
Labels: setting, fix

#13 feat(be): connect db with server
  .env
  .vscode/settings.json
  docker-compose.yaml
  server/Dockerfile
  server/application.properties
  server/build.gradle
  server/src/main/java/com/foolproof/server/controller/TestController.java
  server/src/main/java/com/foolproof/server/controller/UserApiController.java
  server/src/main/java/com/foolproof/server/domain/User.java
  server/src/main/java/com/foolproof/server/dto/UserDTO.java
  server/src/main/java/com/foolproof/server/repository/UserRepository.java
  server/src/main/java/com/foolproof/server/service/UserService.java
  server/src/main/resources/application.properties
  server/src/test/java/com/foolproof/server/controller/UserApiControllerTest.java
Labels: feature, backend
